version: "3.2"

services:
  react-generic-form:
    image: react-generic-form:package
    container_name: react-generic-form-package
    build:
      dockerfile: dev.Dockerfile
      context: ./package
    volumes:
      - "./package/src:/package/src"
      - "./package/dist:/package/dist"
      - "./package/package.json:/app/package.json"
      - "./package/webpack.config.js:/app/webpack.config.js"

  react-generic-form-test:
    image: react-generic-form:test
    container_name: react-generic-form-test
    build:
      dockerfile: dev.Dockerfile
      context: ./app
    ports:
      - "80:80"
    depends_on:
      - react-generic-form
    volumes:
      - "./package:/react-generic-form"
      - "./app/src:/app/src"
      - "./app/entry:/app/entry"
      - "./app/build:/app/build"
      - "./app/package.json:/app/package.json"
      - "./app/webpack.config.js:/app/webpack.config.js"
